In [1]:
import numpy as np
import tqdm
import scipy
import math
from scipy import signal
import os

In [2]:
data = np.load('A01T.npz')

In [3]:
signal = data['s']
etype = data['etyp']
epos = data['epos']
edur = data['edur']

In [4]:
# 每个event单独有一个array，包括这个event在etype中出现位置的index
index769 = np.where(etype == 769)
index769 = index769[0]

index770 = np.where(etype == 770)
index770 = index770[0]

index771 = np.where(etype == 771)
index771 = index771[0]

index772 = np.where(etype == 772)
index772 = index772[0]

index769

array([ 14,  16,  28,  30,  32,  40,  42,  46,  57,  71,  85, 104, 107,
       109, 116, 120, 129, 135, 150, 160, 166, 172, 182, 205, 214, 222,
       224, 239, 247, 259, 271, 273, 279, 289, 301, 305, 310, 312, 324,
       328, 330, 356, 368, 372, 376, 380, 384, 394, 408, 416, 418, 432,
       457, 465, 469, 473, 475, 477, 479, 500, 505, 529, 552, 556, 562,
       566, 572, 576, 585, 593, 597, 602], dtype=int64)

In [5]:
#769
epos769 = []
for i in range(len(index769)):
    epos769.append(epos[index769[i]][0])
    
diff_epos769 = []
for i in range(len(index769)-1):
    diff_epos769.append(epos[index769[i] + 1][0] - epos[index769[i]][0])


    
#770
epos770 = []
for i in range(len(index770)):
    epos770.append(epos[index770[i]][0])
    
diff_epos770 = []
for i in range(len(index770)):
    diff_epos770.append(epos[index770[i] + 1][0] - epos[index770[i]][0])
    

    
#771
epos771 = []
for i in range(len(index771)):
    epos771.append(epos[index771[i]][0])
    
diff_epos771 = []
for i in range(len(index771)):
    diff_epos771.append(epos[index771[i] + 1][0] - epos[index771[i]][0])



#772
epos772 = []
for i in range(len(index772)):
    epos772.append(epos[index772[i]][0])
    
diff_epos772 = []
for i in range(len(index772)):
    diff_epos772.append(epos[index772[i] + 1][0] - epos[index772[i]][0])

In [6]:
len(diff_epos769), len(diff_epos770), len(diff_epos771), len(diff_epos772)

(71, 72, 72, 72)

In [7]:
#每一个event对应edur里的数字 都是313
edur769 = []
for i in range(len(index769)):
    edur769.append(edur[index769[i]][0])
    
edur770 = []
for i in range(len(index770)):
    edur770.append(edur[index770[i]][0])
    
edur771 = []
for i in range(len(index771)):
    edur771.append(edur[index771[i]][0])
    
edur772 = []
for i in range(len(index772)):
    edur772.append(edur[index772[i]][0])

In [8]:
diff = []
for i in range(0, 200):
    x = epos[8+2*i] - epos[7+2*i]
    diff.append(x)
    print(x)

[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[0]
[1412]
[1531]
[1453]
[1461]
[1604]
[1504]
[1475]
[1526]
[1571]
[1607]
[1592]
[1591]
[1543]
[1564]
[1520]
[1472]
[1463]
[1425]
[1581]
[1478]
[1490]
[1619]
[1406]
[1428]
[500]
[500]
[500]
[350]
[1503]
[1418]
[1452]
[1508]
[500]
[500]
[500]
[500]
[0]
[1498]
[1406]
[1395]
[1472]
[1444]
[1467]
[1620]
[1508]
[1566]
[1536]
[1566]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[500]
[0]
[1559]
[1478]
[500]
[0]
[1418]
[500]
[500]
[500]
[500]
[500]
[500]
[0]
[1498]
[1406]
[1395]
[1472]
[1444]
[1467]
[1620]
[1508]
[1566]
[1536]
[1566]
[1570]
[1580]
[1412]
[1531]
[1453]
[1461]
[1604]
[1504]
[1475]
[1526]
[1571]
[1607]
[1592]
[1591]
[1543]
[1564]
[1520]
[1472]
[1463]
[1425]
[1581]
[1478]
[1490]
[1619]
[1406]
[1428]
[1614]
[1559]
[1478]
[500]
[500]
[500]
[500]
[500

In [5]:
def findtype(data, classnum):
    data1 = np.load(data)
    signal = data1['s']
    etype = data1['etyp']
    epos = data1['epos']
    edur = data1['edur']
    x = etype[etype == classnum]
    pa = epos[etype == classnum]
    pd = edur[etype == classnum]
    ps = pa + pd
    sigarr = []
    for i in range(len(pd)):
        sigarr.append(signal[pa[i]:ps[i]])
    finsigarr = np.stack(sigarr, axis= 0)
    
    return finsigarr

In [19]:
def bandpower(data, fs, freqrange):
    
    """Average Power in input signal x.
    **********
    Parameters
    **********
    
    data :Input signal(Time series).
    fs : Sampling frequency.
    frqrange: Frequency range for band power computation.
    """
    
    import numpy as np
    import os
    print(os.listdir())
    from scipy.signal import welch
    from scipy.integrate import simps
    
    
    freqrange= np.asarray(freqrange)
    low, high = freqrange

    
    freqs, psd = welch(data, fs)

    
    freqrange_idx= np.logical_and(freqs >= low, freqs <= high)
    a = psd[freqrange_idx]
    bp = simps(a)

    return bp

In [7]:
def scoref(f, x, fs, y, C):
    print(f)
    bpsum = 0
    for j in range(len(C)):
        bp = bandpower(x[j,:], fs, [f , 35]) # output 3-D matrix 
        if bp == 0:
            db = 0
        else:
            db = 10 * math.log(bp, 10)
        sf = np.corrcoef(db, y)
        bpsum = bpsum + sf
    return sf

In [8]:
def SelectfreqBand(fs, f, signal, i, y, C):
    # default signal structure should be (Trial, Channel, Duration)
    x = signal[i, C, :]
    Fscores = np.apply_along_axis(scoref, 1, f, x, fs, y, C)
    fmax = f[np.argmax(Fscores)] # step 3 
    #step 4 confusion 
    bp1 = bandpower(x, fs, fmax - 0.5, fmax + 0.5) # output 3-D matrix 
    db1 = 10 * math.log(bp1, 10)
    
    if np.corrcoef(db1,y) > 0:
        Multiplier = 1
    else:
        Multiplier = -1
    fscoref = sum(scoref1)
    
    fmax1 = f[np.argmax(Fscores * Multiplier)]
    f0 = fmax1
    f1 = fmax1
    while (scoref(f0-1, x, fs, y, C) * Multiplier
           >= scoref(fmax1, x, fs, y, C) * Multiplier * 0.05):
        f0 = f0 - 1
    while (scoref(f1+1, x, fs, y, C) * Multiplier
           >= scoref(fmax1, x, fs, y, C) * Multiplier * 0.05):
        f1 = f1 +1
       
    return [f0, f1]
    

In [9]:
j = findtype('A01T.npz',769)


In [10]:
C = [0, 7, 11]

In [11]:
f = np.array(range(5,36))
fs = 250

In [12]:
x = np.array(j[0, C, :])

In [63]:
x.dtype

dtype('float64')

In [64]:
x[1,:]

array([ 6.29882812,  4.63867188,  5.37109375,  7.56835938,  6.68945312,
        6.88476562,  3.36914062,  0.73242188,  5.37109375,  6.98242188,
        6.00585938,  3.02734375,  1.41601562, -0.04882812,  4.98046875,
        8.7890625 ,  7.66601562,  3.7109375 ,  5.71289062,  9.1796875 ,
        9.61914062, 10.00976562, -7.8125    , -4.39453125, -0.9765625 ])

In [65]:
f[1]

6

In [114]:
SelectfreqBand(fs, f, j, 0, 769, C)

[5]
['.gitignore', '.ipynb_checkpoints', 'A01E.npz', 'A01T.npz', 'A02E.npz', 'A02T.npz', 'A03E.npz', 'A03T.npz', 'A04E.npz', 'A04T.npz', 'A05E.npz', 'A05T.npz', 'A06E.npz', 'A06T.npz', 'A07E.npz', 'A07T.npz', 'A08E.npz', 'A08T.npz', 'A09E.npz', 'A09T.npz', 'COGS189 Final.ipynb', 'event_table.png', 'exampleplot.png', 'examples', 'iloveos.png', 'LICENSE', 'main.ipynb', 'mi_paradigm.png', 'plot_c3c4cz.py', 'README.md', 'Untitled.ipynb']
['.gitignore', '.ipynb_checkpoints', 'A01E.npz', 'A01T.npz', 'A02E.npz', 'A02T.npz', 'A03E.npz', 'A03T.npz', 'A04E.npz', 'A04T.npz', 'A05E.npz', 'A05T.npz', 'A06E.npz', 'A06T.npz', 'A07E.npz', 'A07T.npz', 'A08E.npz', 'A08T.npz', 'A09E.npz', 'A09T.npz', 'COGS189 Final.ipynb', 'event_table.png', 'exampleplot.png', 'examples', 'iloveos.png', 'LICENSE', 'main.ipynb', 'mi_paradigm.png', 'plot_c3c4cz.py', 'README.md', 'Untitled.ipynb']
['.gitignore', '.ipynb_checkpoints', 'A01E.npz', 'A01T.npz', 'A02E.npz', 'A02T.npz', 'A03E.npz', 'A03T.npz', 'A04E.npz', 'A04T.n

IndexError: index -1 is out of bounds for axis 0 with size 0

In [80]:
f.shape

(31,)

In [81]:
f = np.reshape(f,(31,1))

In [82]:
f

array([[ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35]])

In [84]:
f[0]

array([5])

In [23]:
bandpower(x[1,:],fs,[31,35])

['.gitignore', '.ipynb_checkpoints', 'A01E.npz', 'A01T.npz', 'A02E.npz', 'A02T.npz', 'A03E.npz', 'A03T.npz', 'A04E.npz', 'A04T.npz', 'A05E.npz', 'A05T.npz', 'A06E.npz', 'A06T.npz', 'A07E.npz', 'A07T.npz', 'A08E.npz', 'A08T.npz', 'A09E.npz', 'A09T.npz', 'COGS189 Final.ipynb', 'event_table.png', 'exampleplot.png', 'examples', 'iloveos.png', 'LICENSE', 'main.ipynb', 'mi_paradigm.png', 'plot_c3c4cz.py', 'README.md', 'Untitled.ipynb']


IndexError: index -1 is out of bounds for axis 0 with size 0

In [96]:
np.transpose(x[1,:])

array([ 6.29882812,  4.63867188,  5.37109375,  7.56835938,  6.68945312,
        6.88476562,  3.36914062,  0.73242188,  5.37109375,  6.98242188,
        6.00585938,  3.02734375,  1.41601562, -0.04882812,  4.98046875,
        8.7890625 ,  7.66601562,  3.7109375 ,  5.71289062,  9.1796875 ,
        9.61914062, 10.00976562, -7.8125    , -4.39453125, -0.9765625 ])

In [25]:
help simp

SyntaxError: invalid syntax (Temp/ipykernel_20564/1054874664.py, line 1)